version: "3"
services:
  firebase:
    container_name: ryoheymeeting_firebase
    env_file:
      - .env
    build: .
    volumes:
      - .:/firebase
      - node_modules:/firebase/node_modules
    tty: true
    working_dir: /firebase
    command: yarn start
    ports:
      - 4000:4000 # Emulator Suite UI
      - 9099:9099 # Authentication
      #- 5000:5000 # Firebase Hosting
      #- 5001:5001 # Clound Functions
      - 9000:9000 # Realtime Database
      - 8080:8080 # Cloud Firestore
      - 9199:9199 # Storage
      #- 8085:8085 # Cloud Pub/Sub
      - 4400:4400 # Emuylator Hub
      - 4500:4500 # Other reserved ports
volumes:
  node_modules: